// @artifact production
// GENERATED by tools/stamp-model-id.py -- do not edit by hand.
// sha256 of the application page plus every src/*.js module except this one.
// See docs/dev/V3-PLAN.md sections 4 and 10 (deterministic invariant).
(function (root, factory) {
  if (typeof module === 'object' && module.exports) module.exports = factory();
  else (root.ESS = root.ESS || {}).MODEL_ID = factory();
})(typeof globalThis !== 'undefined' ? globalThis : this, function () {
  'use strict';
  return 'cc0b2a837f7573e40f650c5a637e59c5275522b2ec767aec61efdce1c9ed0e17';
});
